apiVersion: v2
name: mayastor
description: Mayastor Helm chart for Kubernetes
#icon:
#home:
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.0"

dependencies:
  - name: crds
    version: 0.0.0
    condition: crds.enabled
  - name: etcd
    repository: https://charts.bitnami.com/bitnami
    version: 8.6.0
  - name: jaeger-operator
    version: 2.50.1
    repository: https://jaegertracing.github.io/helm-charts
    condition: base.jaeger.enabled
  - name: loki-stack
    version: 2.9.11
    repository: https://grafana.github.io/helm-charts
    condition: loki-stack.enabled
  - name: nats
    version: 0.19.14
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: eventing.enabled
  - name: localpv-provisioner
    version: 4.0.0
    repository: https://openebs.github.io/dynamic-localpv-provisioner
    condition: localpv-provisioner.enabled
