project:
  name: OpenEBS Mayastor
  shortName: Mayastor
  url: https://openebs.io/mayastor
  description: Fast NVMe backed storage for enterprise users on Kubernetes
repository:
  url: https://openebs.github.io/mayastor-extensions/
  name: mayastor
chart:
  name: mayastor
  version: 2.7.0-0-main-unstable-2024-05-16-22-23-02-0
  values: "-- generate from values file --"
  valuesExample: "-- generate from values file --"
prerequisites:
  - "Kubernetes v1.21+"
  - Linux Kernel 5.4+ on Worker Nodes with required nvme modules loaded
release:
  name: mayastor
  namespace: mayastor
