repos:
-   repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.2.0
    hooks:
    -   id: nixpkgs-fmt
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
        exclude: openapi/
-   repo: local
    hooks:
    -   id: rust-lint
        name: Rust lint
        description: Run cargo clippy on files included in the commit.
        entry: nix-shell --pure --run 'cargo-clippy --all --all-targets -- -D warnings'
        pass_filenames: false
        types: [file, rust]
        language: system
    -   id: rust-style
        name: Rust style
        description: Run cargo fmt on files included in the commit.
        entry: nix-shell --pure --run 'cargo-fmt --all -- --check'
        pass_filenames: true
        types: [file, rust]
        language: system
    -   id: commit-lint
        name: Commit Lint
        description: Runs commitlint against the commit message.
        language: system
        entry: bash -c 'nix-shell --pure --run "cat $1 | grep -v '^#' | commitlint"'
        args: [$1]
        stages: [commit-msg]
