{{- if .Values.eventing.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-stats
  labels:
    app: stats
    {{ include "label_prefix" . }}/release: {{ .Release.Name }}
    {{ include "label_prefix" . }}/version: {{ .Chart.Version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats
      {{ include "label_prefix" . }}/release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: stats
        {{ include "label_prefix" . }}/release: {{ .Release.Name }}
        {{ include "label_prefix" . }}/version: {{ .Chart.Version }}
    spec:
      serviceAccountName: {{ .Release.Name }}-service-account
      imagePullSecrets:
        {{- include "base_pull_secrets" . }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: stats
          image: "{{ .Values.image.registry }}/{{ .Values.image.repo }}/{{ .Chart.Name }}-stats:{{ default .Values.image.tag .Values.image.repoTags.extensions }}"
          command:
            - stats
          ports:
            - containerPort: 9090
              protocol: TCP
              name: stats
          env:
            - name: RUST_LOG
              value: {{ .Values.eventing.stats.logLevel }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: {{ .Values.eventing.stats.resources.limits.cpu | quote }}
              memory: {{ .Values.eventing.stats.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.eventing.stats.resources.requests.cpu | quote }}
              memory: {{ .Values.eventing.stats.resources.requests.memory | quote }}
{{- end }}
